=== alikomurcu/ppsurf/source/framework/configSchema.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1">
  <xsd:element name="edge-set">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="configuration" minOccurs="0" maxOccurs="1" type="configurationType"/>
        <xsd:element name="edge" minOccurs="0" maxOccurs="unbounded" type="edgeType"/>
      </xsd:sequence>
      <xsd:attribute name="version" type="versionNumber" default="0.1"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="configurationType">
    <xsd:sequence>
      <xsd:element name="folder" minOccurs="1" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:simpleContent>
            <xsd:extension base="xsd:string">
              <xsd:attribute name="name" type="xsd:string" use="required"/>
            </xsd:extension>
          </xsd:simpleContent>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="edgeType">
    <xsd:sequence>
      <xsd:element name="name" minOccurs="1" maxOccurs="1" type="xsd:string"/>
      <xsd:element name="description" minOccurs="1" maxOccurs="1" type="xsd:string"/>
      <xsd:element name="inputDir" minOccurs="1" maxOccurs="unbounded" type="stringWithFolderPlaceholder"/>
      <xsd:element name="outputDir" minOccurs="1" maxOccurs="unbounded" type="stringWithFolderPlaceholder"/>
      <xsd:element name="call" minOccurs="1" maxOccurs="1" type="stringWithFolderPlaceholder"/>
      <xsd:element name="parameters" minOccurs="1" maxOccurs="1" type="parametersType"/>
    </xsd:sequence>
    <xsd:attribute name="type" type="edgeCategory" default="regular"/>
    <xsd:attribute name="require_complete" type="xsd:boolean"/>
  </xsd:complexType>

  <xsd:complexType name="stringWithFolderPlaceholder">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="useFolder" type="xsd:string"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:complexType name="parametersType">
    <xsd:all>
      <xsd:element name="option" minOccurs="0" maxOccurs="unbounded" type="optionType"/>
      <xsd:element name="argument" minOccurs="0" maxOccurs="unbounded" type="argumentType"/>
    </xsd:all>
  </xsd:complexType>

  <xsd:complexType name="optionType">
    <xsd:attribute name="name" type="xsd:string" use="required"/>
    <xsd:attribute name="type" type="typeType"/>
    <xsd:attribute name="useFolder" type="xsd:string"/>
    <xsd:attribute name="value" type="xsd:string" default=""/>
    <xsd:assert test="(@type and not(@value)) or (not(@type) and @value) or (not(@type) and not(@value))"/>
  </xsd:complexType>

  <xsd:complexType name="argumentType">
    <xsd:attribute name="type" type="typeType"/>
    <xsd:attribute name="useFolder" type="xsd:string"/>
    <xsd:attribute name="value" type="xsd:string" default=""/>
    <xsd:assert test="(@type and not(@value)) or (not(@type) and @value)"/>
  </xsd:complexType>

  <xsd:simpleType name="typeType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="input"/>
      <xsd:enumeration value="output"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="versionNumber">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[0-9].[0-9]"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="edgeCategory">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="regular"/>
      <xsd:enumeration value="unique"/>
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== alikomurcu/ppsurf/source/framework/p2s_abc_modeling_course.xml
<?xml version="1.0" encoding="UTF-8"?>
<edge-set xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="configSchema.xsd" version="0.2">
  <configuration>
    <folder name="data">datasets/abc_modeling</folder>
    <folder name="scripts">source/framework/make_dataset</folder>
  </configuration>

  <edge type="regular">
    <name>Convert meshes</name>
    <description>Converts meshes in other format using trimesh</description>
    <inputDir useFolder="data">00_base_meshes</inputDir>
    <outputDir useFolder="data">01_base_meshes_ply</outputDir>
    <call useFolder="scripts">python {}/convert_mesh.py</call>
    <parameters>
      <option name="-t" value=".ply"/>
      <argument type="input"/>
      <argument type="output"/>
    </parameters>
  </edge>

  <edge type="regular">
    <name>Clean meshes</name>
    <description>Clean the meshes with trimesh</description>
    <inputDir useFolder="data">01_base_meshes_ply</inputDir>
    <outputDir useFolder="data">02_meshes_cleaned</outputDir>
    <call useFolder="scripts">python {}/clean_mesh.py</call>
    <parameters>
      <argument type="input"/>
      <argument type="output"/>
    </parameters>
  </edge>

  <edge type="regular">
    <name>Scale meshes</name>
    <description>Scale the meshes with trimesh</description>
    <inputDir useFolder="data">02_meshes_cleaned</inputDir>
    <outputDir useFolder="data">03_meshes</outputDir>
    <call useFolder="scripts">python {}/scale_mesh.py</call>
    <parameters>
      <argument type="input"/>
      <argument type="output"/>
    </parameters>
  </edge>

  <edge type="regular">
    <name>Sample Surface</name>
    <description>Sample Surface</description>
    <inputDir useFolder="data">03_meshes</inputDir>
    <outputDir useFolder="data">04_pts</outputDir>
    <outputDir useFolder="data">04_pts_vis</outputDir>
    <call useFolder="scripts">python {}/sample_surface.py</call>
    <parameters>
      <option name="--num_samples" value="25000"/>
      <argument type="input"/>
      <argument type="output"/>
      <argument type="output"/>
    </parameters>
  </edge>

  <edge type="regular">
    <name>Get query dist</name>
    <description>Get query dist</description>
    <inputDir useFolder="data">03_meshes</inputDir>
    <outputDir useFolder="data">05_query_dist</outputDir>
    <outputDir useFolder="data">05_query_pts</outputDir>
    <outputDir useFolder="data">05_patch_vis</outputDir>
    <call useFolder="scripts">python {}/get_query_dist.py</call>
    <parameters>
      <argument type="input"/>
      <argument type="output"/>
      <argument type="output"/>
      <argument type="output"/>
    </parameters>
  </edge>

  <edge type="unique" require_complete="true">
    <name>Make file list</name>
    <description>Make file list</description>
    <inputDir useFolder="data">04_pts</inputDir>
    <outputDir useFolder="data">06_splits</outputDir>
    <call useFolder="scripts">python {}/make_dataset_splits.py</call>
    <parameters>
      <option name="--seed" value="42"/>
      <argument type="output"/>
      <argument useFolder="data" value="{}/04_pts"/>
    </parameters>
  </edge>
</edge-set>
